/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by @marko-bindings/tanstack-router.
// Do not edit this file directly.

import {
  lazyRouteComponent,
  createFileRoute,
} from '@marko-bindings/tanstack-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'

const IndexRouteImport = createFileRoute('/')()
const QueryRouteImport = createFileRoute('/query')()

const rootRoute = rootRouteImport.update({
  component: lazyRouteComponent(
    () => import('./routes/__root.component.marko'),
    'default',
  ),
})

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component.marko'),
    'default',
  ),
})

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/about.component.marko'),
    'default',
  ),
})

const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/posts.$postId.component.marko'),
    'default',
  ),
})

const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/query.component.marko'),
    'default',
  ),
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  QueryRoute: QueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@marko-bindings/tanstack-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

export interface FileRouteTypes {
  fileRoutesByFullPath: {
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/posts/$postId': typeof PostsPostIdRoute
    '/query': typeof QueryRoute
  }
  fullPaths: '/' | '/about' | '/posts/$postId' | '/query'
  fileRoutesByTo: {
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/posts/$postId': typeof PostsPostIdRoute
    '/query': typeof QueryRoute
  }
  to: '/' | '/about' | '/posts/$postId' | '/query'
  id: '__root__' | '/' | '/about' | '/posts/$postId' | '/query'
  fileRoutesById: {
    __root__: typeof rootRoute
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/posts/$postId': typeof PostsPostIdRoute
    '/query': typeof QueryRoute
  }
}
